[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"


[project]
name = "endoscopy-capsule-control"
version = "0.1.0"
description = "Simulation and control of a magnetically actuated capsule endoscope using a dual-electromagnet actuation system."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "mujoco",
]


[tool.setuptools.packages.find]
where = ["src"]