"""
Point-dipole magnetic field model for the DEMA electromagnets.

The electromagnet current is signed:

    I > 0  -> dipole moment along +axis
    I < 0  -> dipole moment along -axis

Therefore reversing current reverses the magnetic field.
"""

from __future__ import annotations

import numpy as np

from .capsule_magnet import unit


MU0 = 4.0e-7 * np.pi


def dipole_field(
    p_query: np.ndarray,
    p_em: np.ndarray,
    axis_em: np.ndarray,
    current: float,
    em_gain: float,
) -> np.ndarray:
    """
    Compute the magnetic field generated by one point-dipole
    electromagnet.

    Parameters
    ----------
    p_query
        Query position in world coordinates [m].

    p_em
        Electromagnet dipole position in world coordinates [m].

    axis_em
        Electromagnet magnetic-axis direction in world coordinates.

    current
        Signed electromagnet current [A].

    em_gain
        Effective electromagnet dipole moment per ampere.

        The electromagnet dipole moment is

            m_em = em_gain * current * axis_em

    Returns
    -------
    np.ndarray, shape (3,)
        Magnetic flux density B [T].
    """
    p_query = np.asarray(
        p_query,
        dtype=float,
    )

    p_em = np.asarray(
        p_em,
        dtype=float,
    )

    axis_em = unit(
        axis_em
    )

    r = (
        p_query
        - p_em
    )

    distance = float(
        np.linalg.norm(r)
    )

    if distance < 1e-8:
        raise ValueError(
            "Query point is too close to the "
            "electromagnet point dipole."
        )

    r_hat = (
        r
        / distance
    )

    # Preserve current polarity.
    m_em = (
        float(em_gain)
        * float(current)
        * axis_em
    )

    B = (
        MU0
        / (
            4.0
            * np.pi
            * distance**3
        )
        * (
            3.0
            * np.dot(
                m_em,
                r_hat,
            )
            * r_hat
            - m_em
        )
    )

    return B


def total_field(
    p_query: np.ndarray,
    em_positions,
    em_axes,
    currents,
    em_gain: float,
) -> np.ndarray:
    """
    Compute the total magnetic field generated by all electromagnets.

    Magnetic fields are superposed linearly:

        B_total = sum(B_j)

    Parameters
    ----------
    p_query
        Query position in world coordinates [m].

    em_positions
        Iterable of electromagnet positions.

    em_axes
        Iterable of electromagnet magnetic-axis directions.

    currents
        Iterable of signed coil currents [A].

    em_gain
        Effective electromagnet dipole gain.

    Returns
    -------
    np.ndarray, shape (3,)
        Total magnetic field [T].
    """
    if not (
        len(em_positions)
        == len(em_axes)
        == len(currents)
    ):
        raise ValueError(
            "em_positions, em_axes and currents "
            "must have the same length."
        )

    B_total = np.zeros(
        3,
        dtype=float,
    )

    for (
        p_em,
        axis_em,
        current,
    ) in zip(
        em_positions,
        em_axes,
        currents,
    ):
        B_total += dipole_field(
            p_query=p_query,
            p_em=p_em,
            axis_em=axis_em,
            current=current,
            em_gain=em_gain,
        )

    return B_total
