"""
Current allocation for the dual-electromagnet actuator.

The physical coil currents are represented using common and
differential coordinates:

    Ic = (I1 + I2) / 2
    Id = (I2 - I1) / 2

Therefore:

    I1 = Ic - Id
    I2 = Ic + Id

For a fixed capsule pose and magnetic-moment orientation,
the point-dipole magnetic force is linear in coil currents.

Along a selected control axis:

    F_axis = k_Ic * Ic + k_Id * Id

so the differential current can be solved from

    Id = (F_desired - k_Ic * Ic) / k_Id
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from endoscopy_capsule_control.magnetic import (
    magnetic_wrench,
    unit,
)


@dataclass(frozen=True)
class CurrentAllocationResult:
    """
    Result returned by the current allocator.
    """

    common_current: float
    differential_current: float

    current_1: float
    current_2: float

    common_force_basis: float
    differential_force_basis: float

    requested_force: float
    achieved_force: float

    saturated: bool


def currents_from_common_differential(
    common_current: float,
    differential_current: float,
) -> np.ndarray:
    """
    Convert common/differential currents to physical coil currents.

        I1 = Ic - Id
        I2 = Ic + Id
    """
    ic = float(
        common_current
    )

    id_ = float(
        differential_current
    )

    return np.array(
        [
            ic - id_,
            ic + id_,
        ],
        dtype=float,
    )


def common_differential_from_currents(
    current_1: float,
    current_2: float,
) -> tuple[float, float]:
    """
    Convert physical coil currents to common/differential coordinates.

        Ic = (I1 + I2) / 2
        Id = (I2 - I1) / 2
    """
    i1 = float(
        current_1
    )

    i2 = float(
        current_2
    )

    ic = (
        0.5
        * (
            i1
            + i2
        )
    )

    id_ = (
        0.5
        * (
            i2
            - i1
        )
    )

    return (
        float(ic),
        float(id_),
    )


def force_basis_along_axis(
    p_capsule: np.ndarray,
    capsule_moment_world: np.ndarray,
    em_positions,
    em_axes,
    axis_world: np.ndarray,
    em_gain: float,
    gradient_step: float = 1e-5,
) -> tuple[float, float]:
    """
    Compute force authority of Ic and Id along one selected axis.

    Returns
    -------
    k_ic
        Force generated by Ic = 1 A, Id = 0 A [N/A].

    k_id
        Force generated by Ic = 0 A, Id = 1 A [N/A].
    """
    axis_world = unit(
        axis_world
    )

    currents_ic = (
        currents_from_common_differential(
            common_current=1.0,
            differential_current=0.0,
        )
    )

    F_ic, _, _ = magnetic_wrench(
        p_capsule=p_capsule,
        capsule_moment_world=capsule_moment_world,
        em_positions=em_positions,
        em_axes=em_axes,
        currents=currents_ic,
        em_gain=em_gain,
        gradient_step=gradient_step,
    )

    currents_id = (
        currents_from_common_differential(
            common_current=0.0,
            differential_current=1.0,
        )
    )

    F_id, _, _ = magnetic_wrench(
        p_capsule=p_capsule,
        capsule_moment_world=capsule_moment_world,
        em_positions=em_positions,
        em_axes=em_axes,
        currents=currents_id,
        em_gain=em_gain,
        gradient_step=gradient_step,
    )

    k_ic = float(
        np.dot(
            F_ic,
            axis_world,
        )
    )

    k_id = float(
        np.dot(
            F_id,
            axis_world,
        )
    )

    return (
        k_ic,
        k_id,
    )


class MagneticCurrentAllocator:
    """
    Map desired magnetic force to physical DEMA coil currents.
    """

    def __init__(
        self,
        current_abs_max: float,
        differential_current_min: float,
        differential_current_max: float,
        common_current_abs_max: float,
        gradient_step: float = 1e-5,
    ):
        """
        Parameters
        ----------
        current_abs_max
            Physical absolute current limit for each coil [A].

        differential_current_min
            Minimum allowed Id [A].

        differential_current_max
            Maximum allowed Id [A].

        common_current_abs_max
            Software limit for |Ic| [A].

        gradient_step
            Spatial finite-difference step for magnetic force [m].
        """
        self.current_abs_max = float(
            current_abs_max
        )

        self.differential_current_min = float(
            differential_current_min
        )

        self.differential_current_max = float(
            differential_current_max
        )

        self.common_current_abs_max = float(
            common_current_abs_max
        )

        self.gradient_step = float(
            gradient_step
        )

        if self.current_abs_max <= 0.0:
            raise ValueError(
                "current_abs_max must be positive."
            )

        if (
            self.differential_current_min
            > self.differential_current_max
        ):
            raise ValueError(
                "Invalid differential-current range."
            )

        if (
            abs(self.differential_current_min)
            > self.current_abs_max
            or abs(self.differential_current_max)
            > self.current_abs_max
        ):
            raise ValueError(
                "Differential-current limits must lie "
                "inside physical coil-current limits."
            )

        if self.common_current_abs_max < 0.0:
            raise ValueError(
                "common_current_abs_max cannot be negative."
            )

        if self.gradient_step <= 0.0:
            raise ValueError(
                "gradient_step must be positive."
            )


    def allocate(
        self,
        p_capsule: np.ndarray,
        capsule_moment_world: np.ndarray,
        em_positions,
        em_axes,
        control_axis_world: np.ndarray,
        desired_force: float,
        em_gain: float,
        common_current_request: float = 0.0,
    ) -> CurrentAllocationResult:
        """
        Allocate physical coil currents.

        Parameters
        ----------
        p_capsule
            Estimated capsule position [m].

        capsule_moment_world
            Estimated capsule magnetic moment [A*m^2].

        em_positions
            Electromagnet positions.

        em_axes
            Electromagnet magnetic axes.

        control_axis_world
            Axis along which desired_force is specified.

        desired_force
            Desired magnetic force along control axis [N].

        em_gain
            Magnetic model gain used by the controller.

        common_current_request
            Optional requested Ic [A].

            For pure Z-hover control this can simply be zero.
            A future local stabilizer may provide a nonzero value.

        Returns
        -------
        CurrentAllocationResult
        """
        desired_force = float(
            desired_force
        )

        ic_requested = float(
            common_current_request
        )

        # ----------------------------------------------------
        # 1. Software limit on common current
        # ----------------------------------------------------

        ic_command = float(
            np.clip(
                ic_requested,
                -self.common_current_abs_max,
                +self.common_current_abs_max,
            )
        )

        saturated_common_soft = (
            abs(
                ic_command
                - ic_requested
            )
            > 1e-12
        )

        # ----------------------------------------------------
        # 2. Compute force authority of Ic and Id
        # ----------------------------------------------------

        k_ic, k_id = (
            force_basis_along_axis(
                p_capsule=p_capsule,
                capsule_moment_world=capsule_moment_world,
                em_positions=em_positions,
                em_axes=em_axes,
                axis_world=control_axis_world,
                em_gain=em_gain,
                gradient_step=self.gradient_step,
            )
        )

        if abs(k_id) < 1e-12:
            raise RuntimeError(
                "Differential-current force authority "
                "is approximately zero."
            )

        # ----------------------------------------------------
        # Helper: solve Id for a fixed Ic
        # ----------------------------------------------------

        def solve_differential_current(
            ic_value: float,
        ) -> tuple[float, bool]:
            id_unsaturated = (
                desired_force
                - k_ic
                * ic_value
            ) / k_id

            id_command = float(
                np.clip(
                    id_unsaturated,
                    self.differential_current_min,
                    self.differential_current_max,
                )
            )

            saturated = (
                abs(
                    id_command
                    - id_unsaturated
                )
                > 1e-12
            )

            return (
                id_command,
                saturated,
            )

        # ----------------------------------------------------
        # 3. First Id solution
        # ----------------------------------------------------

        id_command, saturated_id = (
            solve_differential_current(
                ic_command
            )
        )

        # ----------------------------------------------------
        # 4. Enforce physical coil-current reserve
        #
        # I1 = Ic - Id
        # I2 = Ic + Id
        #
        # For symmetric ±Imax coil limits:
        #
        #     |Ic| <= Imax - |Id|
        # ----------------------------------------------------

        common_physical_limit = max(
            0.0,
            self.current_abs_max
            - abs(
                id_command
            ),
        )

        ic_after_reserve = float(
            np.clip(
                ic_command,
                -common_physical_limit,
                +common_physical_limit,
            )
        )

        saturated_common_reserve = (
            abs(
                ic_after_reserve
                - ic_command
            )
            > 1e-12
        )

        ic_command = (
            ic_after_reserve
        )

        # ----------------------------------------------------
        # 5. Re-solve Id if Ic changed
        # ----------------------------------------------------

        (
            id_command,
            saturated_id_second,
        ) = solve_differential_current(
            ic_command
        )

        saturated_id = (
            saturated_id
            or saturated_id_second
        )

        # ----------------------------------------------------
        # 6. Convert to physical coil currents
        # ----------------------------------------------------

        currents = (
            currents_from_common_differential(
                common_current=ic_command,
                differential_current=id_command,
            )
        )

        current_1_before = float(
            currents[0]
        )

        current_2_before = float(
            currents[1]
        )

        current_1 = float(
            np.clip(
                current_1_before,
                -self.current_abs_max,
                +self.current_abs_max,
            )
        )

        current_2 = float(
            np.clip(
                current_2_before,
                -self.current_abs_max,
                +self.current_abs_max,
            )
        )

        saturated_final_clip = (
            abs(
                current_1
                - current_1_before
            )
            > 1e-12
            or abs(
                current_2
                - current_2_before
            )
            > 1e-12
        )

        # Reconstruct final Ic/Id from the actual commands.
        ic_final, id_final = (
            common_differential_from_currents(
                current_1=current_1,
                current_2=current_2,
            )
        )

        achieved_force = (
            k_ic
            * ic_final
            + k_id
            * id_final
        )

        saturated = (
            saturated_common_soft
            or saturated_common_reserve
            or saturated_id
            or saturated_final_clip
        )

        return CurrentAllocationResult(
            common_current=ic_final,
            differential_current=id_final,
            current_1=current_1,
            current_2=current_2,
            common_force_basis=k_ic,
            differential_force_basis=k_id,
            requested_force=desired_force,
            achieved_force=float(
                achieved_force
            ),
            saturated=bool(
                saturated
            ),
        )