"""
Hover controller for the DEMA-actuated magnetic capsule.

This module combines three control components:

1. Z PID + feedforward
       -> desired magnetic force along DEMA local Z

2. Local equilibrium stabilizer
       -> requested common current Ic

3. Magnetic current allocator
       -> coil current commands I1 and I2

The controller contains no MuJoCo-specific dynamics.

The simulation layer is responsible for reading the MuJoCo state
and converting it into HoverControlInput.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np

from .allocator import (
    MagneticCurrentAllocator,
)

from .local_stabilizer import (
    LocalStabilizer,
    LocalStabilizerGains,
    magnetic_moment_tilt_y,
)

from .pid_z import (
    ZPIDController,
    design_z_pid_gains,
)


# ============================================================
# CONTROL INPUT / OUTPUT
# ============================================================


@dataclass(frozen=True)
class HoverControlInput:
    """
    Quantities required by the hover controller.

    All world-frame vectors are expressed in the MuJoCo world frame.

    position_lcs
        Capsule magnetic-center position in DEMA LCS [m].

    position_world
        Capsule magnetic-center position in world frame [m].

    magnetic_moment_lcs
        Capsule permanent magnetic moment in DEMA LCS [A*m^2].

    magnetic_moment_world
        Capsule permanent magnetic moment in world frame [A*m^2].

    em_positions_world
        Two electromagnet-center positions in world frame [m].

    em_axes_world
        Two electromagnet axes in world frame.

    control_axis_world
        DEMA local +Z axis represented in world coordinates.
    """

    position_lcs: np.ndarray

    position_world: np.ndarray

    magnetic_moment_lcs: np.ndarray

    magnetic_moment_world: np.ndarray

    em_positions_world: tuple[
        np.ndarray,
        np.ndarray,
    ]

    em_axes_world: tuple[
        np.ndarray,
        np.ndarray,
    ]

    control_axis_world: np.ndarray


@dataclass(frozen=True)
class HoverControlOutput:
    """
    Result of one hover-controller update.
    """

    current_command: np.ndarray

    desired_force_z: float

    common_current_request: float

    theta_y: float

    allocation: Any

    force_limit_saturated: bool

    integral_accepted: bool


# ============================================================
# HOVER CONTROLLER
# ============================================================


class HoverController:
    """
    Combined hover controller.

    Main task
    ---------
    Regulate capsule local-Z position around z_ref.

    Local stabilization
    -------------------
    Stabilize the coupled local X / orientation mode using
    common current Ic.

    The final currents are generated by MagneticCurrentAllocator.
    """

    def __init__(
        self,
        *,
        mass: float,
        drag_coefficient: float,
        control_dt: float,
        z_ref: float,
        feedforward_force: float,
        desired_force_min: float,
        desired_force_max: float,
        natural_frequency: float,
        damping_ratio: float,
        integral_pole: float,
        derivative_filter_tau: float,
        integral_limit: float,
        pid_force_limit: float,
        local_kx: float,
        local_ktheta: float,
        x_ref: float,
        current_abs_max: float,
        differential_current_min: float,
        differential_current_max: float,
        common_current_abs_max: float,
        magnetic_gradient_step: float,
        magnetic_gain: float,
    ):
        # ====================================================
        # REFERENCES
        # ====================================================

        self.z_ref = float(
            z_ref
        )

        self.x_ref = float(
            x_ref
        )

        self.feedforward_force = float(
            feedforward_force
        )

        self.desired_force_min = float(
            desired_force_min
        )

        self.desired_force_max = float(
            desired_force_max
        )

        self.magnetic_gain = float(
            magnetic_gain
        )

        # ====================================================
        # Z PID
        # ====================================================

        z_gains = design_z_pid_gains(
            mass=float(
                mass
            ),
            drag_coefficient=float(
                drag_coefficient
            ),
            natural_frequency=float(
                natural_frequency
            ),
            damping_ratio=float(
                damping_ratio
            ),
            integral_pole=float(
                integral_pole
            ),
        )

        self.z_controller = (
            ZPIDController(
                gains=z_gains,
                dt=float(
                    control_dt
                ),
                derivative_filter_tau=float(
                    derivative_filter_tau
                ),
                integral_limit=float(
                    integral_limit
                ),
                force_limit=float(
                    pid_force_limit
                ),
            )
        )

        # ====================================================
        # LOCAL EQUILIBRIUM STABILIZER
        # ====================================================

        self.local_stabilizer = (
            LocalStabilizer(
                gains=LocalStabilizerGains(
                    kx=float(
                        local_kx
                    ),
                    ktheta=float(
                        local_ktheta
                    ),
                ),
                common_current_limit=float(
                    common_current_abs_max
                ),
            )
        )

        # ====================================================
        # CURRENT ALLOCATOR
        # ====================================================

        self.allocator = (
            MagneticCurrentAllocator(
                current_abs_max=float(
                    current_abs_max
                ),
                differential_current_min=float(
                    differential_current_min
                ),
                differential_current_max=float(
                    differential_current_max
                ),
                common_current_abs_max=float(
                    common_current_abs_max
                ),
                gradient_step=float(
                    magnetic_gradient_step
                ),
            )
        )

    # ========================================================
    # RESET
    # ========================================================

    def reset(
        self,
        *,
        initial_z: float,
    ) -> None:
        """
        Reset controller state.

        The PID previous error is initialized from the actual
        initial Z position to avoid an artificial derivative kick.
        """

        initial_error = (
            self.z_ref
            - float(
                initial_z
            )
        )

        self.z_controller.reset(
            initial_error=(
                initial_error
            )
        )

    # ========================================================
    # UPDATE
    # ========================================================

    def update(
        self,
        control_input: HoverControlInput,
    ) -> HoverControlOutput:
        """
        Perform one controller update.

        Returns
        -------
        HoverControlOutput
            Final coil-current command and controller diagnostics.
        """

        # ====================================================
        # LOCAL STABILIZER -> Ic
        # ====================================================

        theta_y = (
            magnetic_moment_tilt_y(
                control_input
                .magnetic_moment_lcs
            )
        )

        ic_request = (
            self.local_stabilizer.compute(
                x_measured=float(
                    control_input
                    .position_lcs[0]
                ),
                magnetic_moment_lcs=(
                    control_input
                    .magnetic_moment_lcs
                ),
                x_ref=(
                    self.x_ref
                ),
            )
        )

        # ====================================================
        # Z PID CANDIDATE
        # ====================================================

        z_measured = float(
            control_input
            .position_lcs[2]
        )

        candidate = (
            self.z_controller.prepare(
                z_ref=(
                    self.z_ref
                ),
                z_measured=(
                    z_measured
                ),
            )
        )

        desired_force_candidate = (
            self.feedforward_force
            + candidate.force_candidate
        )

        desired_force_candidate_clipped = float(
            np.clip(
                desired_force_candidate,
                self.desired_force_min,
                self.desired_force_max,
            )
        )

        force_limit_saturated = (
            abs(
                desired_force_candidate_clipped
                - desired_force_candidate
            )
            > 1e-12
        )

        # ====================================================
        # CANDIDATE CURRENT ALLOCATION
        #
        # Used only to determine whether PID integral action
        # should be accepted.
        # ====================================================

        allocation_candidate = (
            self.allocator.allocate(
                p_capsule=(
                    control_input
                    .position_world
                ),
                capsule_moment_world=(
                    control_input
                    .magnetic_moment_world
                ),
                em_positions=[
                    control_input
                    .em_positions_world[0],

                    control_input
                    .em_positions_world[1],
                ],
                em_axes=[
                    control_input
                    .em_axes_world[0],

                    control_input
                    .em_axes_world[1],
                ],
                control_axis_world=(
                    control_input
                    .control_axis_world
                ),
                desired_force=(
                    desired_force_candidate_clipped
                ),
                em_gain=(
                    self.magnetic_gain
                ),
                common_current_request=(
                    ic_request
                ),
            )
        )

        # ====================================================
        # CONDITIONAL INTEGRATION / ANTI-WINDUP
        # ====================================================

        integral_accepted = not (
            force_limit_saturated
            or allocation_candidate.saturated
        )

        pid_force = (
            self.z_controller.finalize(
                accept_integral=(
                    integral_accepted
                )
            )
        )

        # ====================================================
        # FINAL DESIRED MAGNETIC Z FORCE
        # ====================================================

        desired_force_z = (
            self.feedforward_force
            + pid_force
        )

        desired_force_z = float(
            np.clip(
                desired_force_z,
                self.desired_force_min,
                self.desired_force_max,
            )
        )

        # ====================================================
        # FINAL CURRENT ALLOCATION
        # ====================================================

        allocation = (
            self.allocator.allocate(
                p_capsule=(
                    control_input
                    .position_world
                ),
                capsule_moment_world=(
                    control_input
                    .magnetic_moment_world
                ),
                em_positions=[
                    control_input
                    .em_positions_world[0],

                    control_input
                    .em_positions_world[1],
                ],
                em_axes=[
                    control_input
                    .em_axes_world[0],

                    control_input
                    .em_axes_world[1],
                ],
                control_axis_world=(
                    control_input
                    .control_axis_world
                ),
                desired_force=(
                    desired_force_z
                ),
                em_gain=(
                    self.magnetic_gain
                ),
                common_current_request=(
                    ic_request
                ),
            )
        )

        current_command = np.array(
            [
                allocation.current_1,
                allocation.current_2,
            ],
            dtype=float,
        )

        # ====================================================
        # OUTPUT
        # ====================================================

        return HoverControlOutput(
            current_command=(
                current_command
            ),
            desired_force_z=(
                desired_force_z
            ),
            common_current_request=(
                ic_request
            ),
            theta_y=(
                theta_y
            ),
            allocation=(
                allocation
            ),
            force_limit_saturated=(
                force_limit_saturated
            ),
            integral_accepted=(
                integral_accepted
            ),
        )